# Generated by Django 4.1.5 on 2023-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='green', max_length=6)),
                ('cliente', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='E-Mail')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço completo')),
            ],
            options={
                'ordering': ('cliente',),
            },
        ),
    ]
