# Generated by Django 4.1.5 on 2023-01-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('---', '---'), ('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='---', max_length=6),
        ),
    ]
