# Generated by Django 4.1.5 on 2023-01-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('---', '---'), ('Pessoa Física', 'Pessoa Física'), ('Pessoa Juridica', 'Pessoa Jurídica')], default='---', max_length=50),
        ),
    ]
