# Generated by Django 4.1.5 on 2023-01-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria_produto_data_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
