# Generated by Django 4.1.5 on 2023-01-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_categoria_remove_produto_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque_minimo',
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
