# Generated by Django 3.2.16 on 2023-09-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
